const CONCEPT = {
  COMPRAS: 'C. mercaderías',
  ALQUILER: 'ALQUILER',
};

const COLUMNS_INVOICES = {
  COMPRAS: 'COMPRAS',
  AUTONOMOS: 'AUTONOMOS',
  SALARIO: 'SALARIO',
  ALQUILER: 'ALQUILER',
  SUMINISTROS: 'SUMINISTROS',
  COMISIONES: 'COMISIONES',
  TRIBUTOS: 'TRIBUTOS',
  REPARACION: 'REPARACION',
  SEGUROS: 'SEGUROS',
  OTROS: 'OTROS',
};

module.exports = {
  CONCEPT,
  COLUMNS_INVOICES,
};
